### ISSUE TITLE
Not able to capture payments with Razorpay ionic plugin 

### ISSUE THREAD

**Issue by maxakash** [razorpay/razorpay-cordova#102]
I am using Razorpay ionic plugin in my Ionic 3 App. Everything is working fine and I am able to pay via razorpay but the payments are only getting authorized but NOT CAPTURED automatically.
I also tried using  "payment_capture: 1" but still payments are not getting captured automatically.
I am using plugin version 1.4.5

**Comment by pronav** [comment]
Payment capture is a acknowledgement from your side that the payment you've received is correct i.e. not tempered with. It is supposed to be performed on backend side because frontend is inherently insecure for these kind of operations.

You can do one of these:
1. Once payment is successful, pass `payment_id` to your backend and perform capture there
2. Use [Orders API](https://razorpay.com/docs/orders), pass `payment_capture: 1` while creating order, and pass generated `order_id` in payment options on ionic side.
