### ISSUE TITLE
while loading bank page payment stuck 

### ISSUE THREAD

**Issue by aniketkale** [razorpay/razorpay-cordova#91]
* **Common to Both platforms :-**

  - [x] I have gone through the README(https://github.com/razorpay/razorpay-cordova)
  - [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-cordova/issues)
  - [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-cordova/releases)
  - [x] I have cleaned my project.

* **Specific to iOS Users :-**
  - [x] I have modified the module map as specified in the readme (https://github.com/razorpay/razorpay-cordova)
  - [x] I have deleted the contents of the derived data folder and rebuild it.

**Comment by aniketkale** [comment]
Please wait while we redirect you to your bank page app goes pause and payment aloso pause

**Comment by KishoreTorlakonda** [comment]
hi @aniketkale, did you find any solution for this problem?. I am also facing the same issue.

**Comment by iThink32** [comment]
@KishoreTorlakonda please use our latest SDK mentioned in the readme and try again.

**Comment by KishoreTorlakonda** [comment]
Hi @iThink32, Yes I am using the latest SDK(v1.4.1). This is the issue that is thrown when the RP is trying to open a iframe
`Uncaught DOMException: Blocked a frame with origin "https://api.razorpay.com" from accessing a cross-origin frame.
    at $i.write (https://checkout.razorpay.com/v1/checkout-frame.js:1:44820)
    at Ea.writePopup (https://checkout.razorpay.com/v1/checkout-frame.js:1:59841)
    at Ea.generate (https://checkout.razorpay.com/v1/checkout-frame.js:1:58032)
    at new Ea (https://checkout.razorpay.com/v1/checkout-frame.js:1:56582)
    at Zn.Ma.createPayment (https://checkout.razorpay.com/v1/checkout-frame.js:1:60415)
    at Al.submit (https://checkout.razorpay.com/v1/checkout-frame.js:1:276709)
    at Al.preSubmit (https://checkout.razorpay.com/v1/checkout-frame.js:1:274020)
    at HTMLFormElement.a (https://checkout.razorpay.com/v1/checkout-frame.js:1:2394)`

we are using ionic4 and it is using webview(ionic-cordova-webview[v2.3.2]) which is now serving from the app from localhost:8080 in cordova webview instead of the file strategy which was used in the previous ionic-cordova-webview version(1.2.0). We were the same package in ionic3 and it was working fine. Will try to fix this from my side, it would also be better if you can provide inputs from your side. 
<img width="306" alt="screenshot 2019-01-28 at 6 37 23 pm" src="https://user-images.githubusercontent.com/39156047/51838277-d5db5d80-232b-11e9-9784-d283b5ab4cb3.png">

**Comment by KishoreTorlakonda** [comment]
my bad. figured the issue. We are using the same window.Razorpay global object used in the browser instead of 'RazorpayCheckout' obj for cordova app. Anyways thank you all.

**Comment by iThink32** [comment]
closing this issue as it is fixed.Reopen if required.

**Comment by NAgrawal1798** [comment]
When we pay through upi mode after successful payment upi razorpay loading screen got stuck and after closing razporpay screen it shows payment status screen

**Comment by vivekshindhe** [comment]
@NAgrawal1798 will need a bit more info here. When you say it's happening on webview what exactly does that mean?

**Comment by deepak-glad** [comment]
> 

I also facing same issue !
Please help
@ShikharRazorPay
